"""
Tests unitarios para Foreign Language Bindings

Jira: TASK-103
Historia: US-23 (Package Manager)
Fecha: 2025-12-10
"""

import pytest
from src.compiler.bindings import JSBinding, BindingParser
from src.compiler.types import Type, FunctionType


class TestJSBindings:
    """Suite de tests para bindings de JavaScript."""

    def setup_method(self):
        """Configurar cada test."""
        self.parser = BindingParser()

    def test_parse_js_binding_decorator(self):
        """Test parsing del decorador @js_binding."""
        code = '''
        @js_binding("lodash")
        module Lodash {
            @pure
            fn chunk<T>(array: List<T>, size: Number) -> List<List<T>> { }
        }
        '''

        binding = self.parser.parse(code)
        assert binding.language == "js"
        assert binding.library == "lodash"
        assert binding.is_pure == True

    def test_parse_function_signature(self):
        """Test parsing de firmas de función en bindings."""
        code = '''
        @js_binding("axios")
        module Axios {
            @pure
            fn get(url: String, config: Option<Dict<String, Any>>) -> Result<Response, Error> { }
        }
        '''

        binding = self.parser.parse(code)
        func = binding.functions[0]

        assert func.name == "get"
        assert len(func.params) == 2
        assert func.return_type.name == "Result"

    def test_validate_pure_contracts(self):
        """Test validación de contratos puros en bindings."""
        # Binding puro válido
        pure_binding = JSBinding(
            name="lodash",
            functions=[
                FunctionType(
                    name="chunk",
                    params=[Type("List", [Type("T")]), Type("Number")],
                    return_type=Type("List", [Type("List", [Type("T")])]),
                    is_pure=True
                )
            ]
        )

        assert self.parser.validate_pure_contract(pure_binding) == True

    def test_binding_type_mapping(self):
        """Test mapeo de tipos entre Vela y JS."""
        vela_types = {
            "String": "string",
            "Number": "number",
            "Bool": "boolean",
            "List<T>": "Array<T>",
            "Dict<K,V>": "Record<K,V>",
            "Option<T>": "T | null",
            "Result<T,E>": "T | Error"
        }

        for vela_type, js_type in vela_types.items():
            assert self.parser.map_type_to_js(vela_type) == js_type

    def test_generate_js_glue_code(self):
        """Test generación de código glue para JS."""
        binding = JSBinding(
            name="lodash",
            functions=[
                FunctionType(
                    name="chunk",
                    params=[Type("List", [Type("T")]), Type("Number")],
                    return_type=Type("List", [Type("List", [Type("T")])]),
                    is_pure=True
                )
            ]
        )

        glue_code = self.parser.generate_js_glue(binding)

        expected = '''
// Generated by Vela compiler for lodash binding
const lodash = require('lodash');

function vela_lodash_chunk(array, size) {
  return lodash.chunk(array, size);
}

module.exports = {
  vela_lodash_chunk
};
'''

        assert glue_code.strip() == expected.strip()

    def test_binding_error_handling(self):
        """Test manejo de errores en bindings."""
        # Binding con función impura (debería fallar)
        impure_binding = JSBinding(
            name="axios",
            functions=[
                FunctionType(
                    name="post",
                    params=[Type("String"), Type("Any")],
                    return_type=Type("Promise", [Type("Response")]),
                    is_pure=False  # HTTP calls no son puros
                )
            ]
        )

        with pytest.raises(ValueError, match="Impure function in pure binding"):
            self.parser.validate_pure_contract(impure_binding)

    def test_multiple_bindings_in_module(self):
        """Test múltiples bindings en un mismo módulo."""
        code = '''
        @js_binding("lodash")
        @js_binding("axios")
        module Utils {
            @pure
            fn chunk(array: List<Any>, size: Number) -> List<List<Any>> { }

            fn get(url: String) -> Result<Response, Error> { }
        }
        '''

        bindings = self.parser.parse_multiple(code)

        assert len(bindings) == 2
        assert bindings[0].library == "lodash"
        assert bindings[1].library == "axios"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])